### ISSUE TITLE
The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive.

### ISSUE THREAD

**Issue by bharatpaliwal-169** [adrianhajdin/zoom-clone#1]
`
The 'border-border' class does not exist. If 'border-border' is a custom class, make sure it is defined within a '@layer' directive.
`

This is a very weird shadcn and tailwind css config issue. There is no real fix and RCA of why this happens. The possible workarounds to tackle this issue is as follows:

- Check in root directory that you have `tailwind.config.ts` and no `tailwind.config.js` , if it's there just delete that.
- Delete the `node-modules` folder and do `npm i` then do `npx shadcn-ui@latest init` again and this should resolve the error.

**Comment by getFrontend** [comment]
If some custom class is not found, you just need to write it in the config, and everything will work 😎

**Comment by bharatpaliwal-169** [comment]
I already resolved the problem on own, I mentioned this issue so that, anyone setting up the env. gets' struck with this problem knows how to tackle this since it's an unexpected error.
