### ISSUE TITLE
Attempted import error: 'SWRConfig' is not exported from 'swr' (imported as 'SWRConfig').

### ISSUE THREAD

**Issue by Rahul4dev** [adrianhajdin/zoom-clone#8]
Whenever I start the server, it gives this error.

![error1](https://github.com/adrianhajdin/zoom-clone/assets/114183358/ce12be0a-d2e7-4738-82fc-f4deb09f87e3)

And on the terminal, I get this error,

![errorInTerminal](https://github.com/adrianhajdin/zoom-clone/assets/114183358/91dbf323-3818-48bf-9c1e-7d53403134b4)

Please resolve this error @adrianhajdin @TidbitsJS 
Thanks.

**Comment by Satora1** [comment]
just copy this ``import Image from 'next/image';
import Link from 'next/link';
import { SignedIn, UserButton } from '@clerk/nextjs';

import MobileNav from './MobileNav';

const Navbar = () => {
  return (
    <nav className="flex-between fixed z-50 w-full bg-dark-1 px-6 py-4 lg:px-10">
      <Link href="/" className="flex items-center gap-1">
        <Image
          src="/icons/logo.svg"
          width={32}
          height={32}
          alt="yoom logo"
          className="max-sm:size-10"
        />
        <p className="text-[26px] font-extrabold text-white max-sm:hidden">
          YOOM
        </p>
      </Link>
      <div className="flex-between gap-5">
        <SignedIn>
          <UserButton afterSignOutUrl="/sign-in" />
        </SignedIn>

        <MobileNav />
      </div>
    </nav>
  );
};

export default Navbar;``
i dont know how but it works wneh i copy it from repo XD

**Comment by Satora1** [comment]
basically if you delate the <signedOut> it will work , there is some error in this component i dont know why but it work

**Comment by Rahul4dev** [comment]
Yes, it's because of the import statement of SignIn and IserButton which was wrongly imported. It should be from @clerk/nextjs. 

Thanks @navneetp1  and @Satora1
